log_level = "warn"
outputs = "All"
position = "Top"
app_launcher_cmd = "walker"

[modules]
left = [["Workspaces", "KeyboardLayout"]]
center = ["Tempo"]
right = [["Tray", "DisableLaptopScreen", "SystemInfo", "Settings"]]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[system_info]
indicators = ["Cpu", "Temperature", "Memory", { Disk = "/" }]

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[keyboard_layout.labels]
"English (US, intl., with dead keys)" = "ðŸ‡ºðŸ‡¸"
"Spanish" = "ðŸ‡ªðŸ‡¸"

[tempo]
clock_format = "%a %d %b %X"
weather_location = "Current"

[settings]
indicators = [
  "IdleInhibitor",
  "PowerProfile",
  "Audio",
  "Bluetooth",
  "Network",
  "Vpn",
  "Battery",
]
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[[CustomModule]]
name = "DisableLaptopScreen"
icon = "ó°Œ¢"
command = "/home/victor/.config/hypr/scripts/laptopLidClose.sh"
listen_cmd = '''
sh -c '
while true; do
  hyprctl monitors all | grep -A30 "Monitor eDP-1" | grep -q "disabled: false"
  if [ $? -eq 0 ]; then
    echo "{\"text\":\"\",\"alt\":\"enabled\"}"
  else
    echo "{\"text\":\"\",\"alt\":\"disabled\"}"
  fi
  sleep 2
done
'
'''
icons.'enabled' = "ó°Œ¢"
icons.'disabled' = "ó°›§"



[appearance]
style = "Solid"
opacity = 0.5
scale_factor = 1.15
primary_color = "#ADD18D"
success_color = "#9ece6a"
workspace_colors = ["#ADD18D"]

[appearance.danger_color]
base = "#f7768e"
weak = "#e0af68"
