[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'Swww'
prefix = '@'
swww_options = ["--transition-type", "center"]

[config.reload_apps_list]
# kitty = true
# gtk_theme = true
# dunst = true

[templates.bing]
input_path = "~/.config/matugen/templates/bingname-colors.css"
output_path = "~/.config/hypr/style/colors.css"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.themes/victorballester7/colors.css"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/hypr.d/10_colors.conf"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/hyprlock.d/00-colors.conf"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.wlogout]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/wlogout/colors.css"
